# Generated by Django 4.2.6 on 2023-10-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("tel", models.IntegerField(max_length=100)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("field_of_study", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("sleep_time", models.PositiveIntegerField()),
            ],
        ),
    ]
